### ISSUE TITLE
Eval Code

### ISSUE THREAD

**Issue by nisargshah1999** [amazon-science/polygon-transformer#14]
I installed everything as expected and can Import Fairseq but while running code it gives following error, would be great if you could help resolve it

Traceback (most recent call last):
  File "../../evaluate.py", line 13, in <module>
    from fairseq import distributed_utils, options, tasks, utils
  File "/mnt/store/check/research/segment_viu5/polygon-transformer/fairseq/fairseq/tasks/__init__.py", line 15, in <module>
    from .fairseq_task import FairseqTask, LegacyFairseqTask  # noqa
  File "/mnt/store/check/research/segment_viu5/polygon-transformer/fairseq/fairseq/tasks/fairseq_task.py", line 13, in <module>
    from fairseq import metrics, search, tokenizer, utils
ImportError: cannot import name 'metrics' from 'fairseq' (unknown location)

**Comment by joellliu** [comment]
Hi, have you tried reinstalling fairseq? 
https://github.com/amazon-science/polygon-transformer#installation

> python -m pip install pip==21.2.4
pip uninstall fairseq
pip install -r requirements.txt
